// ── Users ──────────────────────────────────────────────────────────────────
export const mockUsers = [
  {
    id: "1",
    name: "Praise Egbo",
    email: "praise@example.com",
    role: "Super Admin",
    aiEnabled: true,
    joinDate: "2024-01-15",
  },
  {
    id: "2",
    name: "Sarah Thompson",
    email: "sarah@example.com",
    role: "Admin",
    aiEnabled: true,
    joinDate: "2024-02-20",
  },
  {
    id: "3",
    name: "Michael Chen",
    email: "michael@example.com",
    role: "User",
    aiEnabled: false,
    joinDate: "2024-03-10",
  },
  {
    id: "4",
    name: "Amara Johnson",
    email: "amara@example.com",
    role: "User",
    aiEnabled: true,
    joinDate: "2024-04-05",
  },
  {
    id: "5",
    name: "David Osei",
    email: "david@example.com",
    role: "User",
    aiEnabled: false,
    joinDate: "2024-05-12",
  },
  {
    id: "6",
    name: "Grace Williams",
    email: "grace@example.com",
    role: "Admin",
    aiEnabled: true,
    joinDate: "2024-06-08",
  },
  {
    id: "7",
    name: "Emmanuel Adu",
    email: "emmanuel@example.com",
    role: "User",
    aiEnabled: false,
    joinDate: "2024-07-22",
  },
  {
    id: "8",
    name: "Joy Mensah",
    email: "joy@example.com",
    role: "User",
    aiEnabled: true,
    joinDate: "2024-08-14",
  },
  {
    id: "9",
    name: "Daniel Park",
    email: "daniel@example.com",
    role: "User",
    aiEnabled: false,
    joinDate: "2024-09-01",
  },
  {
    id: "10",
    name: "Faith Adesanya",
    email: "faith@example.com",
    role: "User",
    aiEnabled: true,
    joinDate: "2024-10-18",
  },
];

// ── Prayer Requests ─────────────────────────────────────────────────────────
export const mockPrayerRequests = [
  {
    id: "1",
    title: "Healing for my mother",
    category: "Health",
    status: "Pending",
    submittedDate: "2025-01-10",
    submittedBy: "Grace Williams",
    content:
      "Please pray for my mother who is undergoing surgery next week. We trust God for a complete healing and recovery.",
  },
  {
    id: "2",
    title: "Financial breakthrough",
    category: "Finance",
    status: "In Progress",
    submittedDate: "2025-01-08",
    submittedBy: "Anonymous",
    content:
      "I am going through financial difficulties and need divine intervention. Please agree with me in prayer.",
  },
  {
    id: "3",
    title: "Peace in my family",
    category: "Family",
    status: "Prayed",
    submittedDate: "2025-01-05",
    submittedBy: "Michael Chen",
    content: "There has been conflict in my family. I pray for restoration of peace and unity.",
  },
  {
    id: "4",
    title: "Career direction",
    category: "Career",
    status: "Pending",
    submittedDate: "2025-01-12",
    submittedBy: "David Osei",
    content: "I am at a crossroads in my career. I need God's direction on which path to take.",
  },
  {
    id: "5",
    title: "Academic success",
    category: "Education",
    status: "In Progress",
    submittedDate: "2025-01-11",
    submittedBy: "Joy Mensah",
    content:
      "Please pray for my exams coming up this month. I need divine wisdom and understanding.",
  },
  {
    id: "6",
    title: "Safe travels",
    category: "Travel",
    status: "Prayed",
    submittedDate: "2025-01-04",
    submittedBy: "Emmanuel Adu",
    content: "I will be traveling internationally next week. Please pray for my safety.",
  },
  {
    id: "7",
    title: "New job opportunity",
    category: "Career",
    status: "Pending",
    submittedDate: "2025-01-13",
    submittedBy: "Anonymous",
    content: "I've been searching for work for months. Please pray that God opens doors for me.",
  },
  {
    id: "8",
    title: "Spiritual growth",
    category: "Spiritual",
    status: "In Progress",
    submittedDate: "2025-01-09",
    submittedBy: "Faith Adesanya",
    content: "I want to grow deeper in my faith and relationship with God. Please pray for me.",
  },
];

// ── Community Posts ─────────────────────────────────────────────────────────
export const mockPosts = [
  {
    id: "1",
    author: { name: "Praise Egbo", email: "praise@example.com" },
    content:
      "God has been so faithful this week! I got the promotion I've been praying for. All glory to Him!",
    category: "Testimonies",
    status: "Active",
    timestamp: "2025-01-13T10:30:00",
    amen: 24,
    praying: 5,
    encouraged: 18,
    flags: 0,
    aiStatus: "Approved",
  },
  {
    id: "2",
    author: { name: "Sarah Thompson", email: "sarah@example.com" },
    content:
      "Can we please lift up the situation in our country in prayer? There is so much turmoil and people need hope.",
    category: "Prayer Points",
    status: "Active",
    timestamp: "2025-01-13T09:15:00",
    amen: 45,
    praying: 32,
    encouraged: 12,
    flags: 0,
    aiStatus: "Approved",
  },
  {
    id: "3",
    author: { name: "Anonymous", email: "anon@example.com" },
    content: "This is a test post that was flagged for review.",
    category: "General",
    status: "Pending",
    timestamp: "2025-01-13T08:00:00",
    amen: 0,
    praying: 0,
    encouraged: 0,
    flags: 2,
    aiStatus: "Rejected",
  },
  {
    id: "4",
    author: { name: "Michael Chen", email: "michael@example.com" },
    content:
      "I just finished reading Proverbs 31 and I'm blown away by the wisdom in God's Word. Share a verse that blessed you!",
    category: "Bible Study",
    status: "Active",
    timestamp: "2025-01-12T20:00:00",
    amen: 15,
    praying: 3,
    encouraged: 22,
    flags: 0,
    aiStatus: "Approved",
  },
  {
    id: "5",
    author: { name: "Amara Johnson", email: "amara@example.com" },
    content: "Looking for an accountability partner for daily prayer. Who's interested?",
    category: "Community",
    status: "Active",
    timestamp: "2025-01-12T18:30:00",
    amen: 8,
    praying: 12,
    encouraged: 5,
    flags: 0,
    aiStatus: "Approved",
  },
  {
    id: "6",
    author: { name: "David Osei", email: "david@example.com" },
    content:
      "Today's devotional really hit home. God's timing is perfect, even when we don't understand it.",
    category: "General",
    status: "Flagged",
    timestamp: "2025-01-12T14:00:00",
    amen: 3,
    praying: 1,
    encouraged: 2,
    flags: 3,
    aiStatus: "Approved",
  },
  {
    id: "7",
    author: { name: "Grace Williams", email: "grace@example.com" },
    content:
      "ENFIRED conference was absolutely amazing! Still processing everything God spoke to us. Who else was there?",
    category: "Events",
    status: "Active",
    timestamp: "2025-01-11T22:00:00",
    amen: 67,
    praying: 4,
    encouraged: 43,
    flags: 0,
    aiStatus: "Approved",
  },
  {
    id: "8",
    author: { name: "Emmanuel Adu", email: "emmanuel@example.com" },
    content: "Post removed for policy violation.",
    category: "General",
    status: "Removed",
    timestamp: "2025-01-10T10:00:00",
    amen: 0,
    praying: 0,
    encouraged: 0,
    flags: 5,
    aiStatus: "Rejected",
  },
];

// ── Community Categories ────────────────────────────────────────────────────
export const mockCategories = [
  {
    id: "1",
    name: "Testimonies",
    description: "Share how God has moved in your life",
    postCount: 142,
    active: true,
  },
  {
    id: "2",
    name: "Prayer Points",
    description: "Shared prayer needs and intercession",
    postCount: 98,
    active: true,
  },
  {
    id: "3",
    name: "Bible Study",
    description: "Scripture discussion and insights",
    postCount: 76,
    active: true,
  },
  {
    id: "4",
    name: "Community",
    description: "General fellowship and connection",
    postCount: 231,
    active: true,
  },
  {
    id: "5",
    name: "Events",
    description: "Conference and event discussions",
    postCount: 54,
    active: true,
  },
  {
    id: "6",
    name: "General",
    description: "Miscellaneous community posts",
    postCount: 315,
    active: true,
  },
  {
    id: "7",
    name: "Archive",
    description: "Old posts category (deprecated)",
    postCount: 23,
    active: false,
  },
];

// ── Notifications ───────────────────────────────────────────────────────────
export const mockNotifications = [
  {
    id: "1",
    title: "ENFIRED Conference Reminder",
    body: "Don't forget! ENFIRED 2025 is happening this weekend.",
    targetRoles: ["User", "Admin"],
    type: "Instant",
    status: "Sent",
    created: "2025-01-10",
    createdBy: "Praise Egbo",
    scheduledFor: null,
  },
  {
    id: "2",
    title: "New Word of the Week",
    body: "This week's word from Bishop Oyedepo is now available!",
    targetRoles: ["User", "Admin", "Super Admin"],
    type: "Scheduled",
    status: "Scheduled",
    created: "2025-01-12",
    createdBy: "Sarah Thompson",
    scheduledFor: "2025-01-14 08:00",
  },
  {
    id: "3",
    title: "Community Feature Update",
    body: "We've added new features to the community section. Check it out!",
    targetRoles: ["User"],
    type: "Instant",
    status: "Sent",
    created: "2025-01-08",
    createdBy: "Praise Egbo",
    scheduledFor: null,
  },
  {
    id: "4",
    title: "Prayer Wall Response",
    body: "Someone replied to your prayer request.",
    targetRoles: ["User"],
    type: "Instant",
    status: "Draft",
    created: "2025-01-13",
    createdBy: "Grace Williams",
    scheduledFor: null,
  },
  {
    id: "5",
    title: "AYAC 2026 Registration Open",
    body: "Africa Youth Aflame Conference registration is now open!",
    targetRoles: ["User", "Admin", "Super Admin"],
    type: "Instant",
    status: "Sent",
    created: "2025-01-05",
    createdBy: "Praise Egbo",
    scheduledFor: null,
  },
  {
    id: "6",
    title: "Weekly Bible Plan",
    body: "Your weekly Bible reading plan is ready.",
    targetRoles: ["User"],
    type: "Recurring",
    status: "Scheduled",
    created: "2025-01-01",
    createdBy: "Sarah Thompson",
    scheduledFor: "Every Mon @ 8AM",
  },
];

// ── SOD Waitlist ────────────────────────────────────────────────────────────
export const mockWaitlist = [
  {
    id: "1",
    name: "David Osei",
    email: "david@example.com",
    phone: "+1 647-555-0123",
    track: "Leadership",
    signedUp: "2024-12-01",
    message: "I've been passionate about leadership development for years.",
  },
  {
    id: "2",
    name: "Joy Mensah",
    email: "joy@example.com",
    phone: "+1 416-555-0456",
    track: "Ministry",
    signedUp: "2024-12-05",
    message: "",
  },
  {
    id: "3",
    name: "Emmanuel Adu",
    email: "emmanuel@example.com",
    phone: "+1 905-555-0789",
    track: "Career",
    signedUp: "2024-12-08",
    message: "Looking to align my career with God's purpose.",
  },
  {
    id: "4",
    name: "Faith Adesanya",
    email: "faith@example.com",
    phone: "+1 778-555-0321",
    track: "Marriage",
    signedUp: "2024-12-10",
    message: "My spouse and I want to strengthen our marriage.",
  },
  {
    id: "5",
    name: "Daniel Park",
    email: "daniel@example.com",
    phone: "+1 604-555-0654",
    track: "General",
    signedUp: "2024-12-12",
    message: "",
  },
  {
    id: "6",
    name: "Amara Johnson",
    email: "amara@example.com",
    phone: "+1 587-555-0987",
    track: "Leadership",
    signedUp: "2024-12-15",
    message: "Ready to step into God's purpose for my life.",
  },
  {
    id: "7",
    name: "Michael Chen",
    email: "michael@example.com",
    phone: "+1 250-555-0147",
    track: "Career",
    signedUp: "2024-12-18",
    message: "",
  },
  {
    id: "8",
    name: "Grace Williams",
    email: "grace@example.com",
    phone: "+1 514-555-0258",
    track: "Ministry",
    signedUp: "2024-12-20",
    message: "Called to full-time ministry and want to be equipped.",
  },
  {
    id: "9",
    name: "Sarah Thompson",
    email: "sarah@example.com",
    phone: "+1 613-555-0369",
    track: "General",
    signedUp: "2024-12-22",
    message: "Excited to grow in all areas of life.",
  },
  {
    id: "10",
    name: "Joshua Mensah",
    email: "joshua@example.com",
    phone: "+1 780-555-0741",
    track: "Leadership",
    signedUp: "2024-12-25",
    message: "",
  },
];

// ── AYAC 2026 ───────────────────────────────────────────────────────────────
export const mockAYAC = [
  {
    id: "1",
    name: "Praise Egbo",
    gender: "M",
    email: "praise@example.com",
    phone: "+1 647-555-0123",
    memberType: "WCI",
    branch: "Toronto Central",
    province: "Ontario",
    attendance: "Yes",
    accommodation: true,
    transportation: false,
    volunteering: true,
    dietary: "None",
    registered: "2025-01-01",
  },
  {
    id: "2",
    name: "Sarah Thompson",
    gender: "F",
    email: "sarah@example.com",
    phone: "+1 416-555-0456",
    memberType: "WCI",
    branch: "Mississauga",
    province: "Ontario",
    attendance: "Yes",
    accommodation: false,
    transportation: true,
    volunteering: false,
    dietary: "Vegetarian",
    registered: "2025-01-02",
  },
  {
    id: "3",
    name: "James Okafor",
    gender: "M",
    email: "james@external.com",
    phone: "+1 905-555-0789",
    memberType: "External",
    branch: "N/A",
    province: "Ontario",
    attendance: "Maybe",
    accommodation: true,
    transportation: true,
    volunteering: false,
    dietary: "None",
    registered: "2025-01-03",
  },
  {
    id: "4",
    name: "Amara Johnson",
    gender: "F",
    email: "amara@example.com",
    phone: "+1 778-555-0321",
    memberType: "WCI",
    branch: "Vancouver",
    province: "British Columbia",
    attendance: "Yes",
    accommodation: true,
    transportation: false,
    volunteering: true,
    dietary: "Gluten-free",
    registered: "2025-01-04",
  },
  {
    id: "5",
    name: "Michael Chen",
    gender: "M",
    email: "michael@example.com",
    phone: "+1 604-555-0654",
    memberType: "WCI",
    branch: "Vancouver",
    province: "British Columbia",
    attendance: "No",
    accommodation: false,
    transportation: false,
    volunteering: false,
    dietary: "None",
    registered: "2025-01-05",
  },
  {
    id: "6",
    name: "Linda Osei",
    gender: "F",
    email: "linda@external.com",
    phone: "+1 587-555-0987",
    memberType: "External",
    branch: "N/A",
    province: "Alberta",
    attendance: "Yes",
    accommodation: true,
    transportation: true,
    volunteering: true,
    dietary: "Halal",
    registered: "2025-01-06",
  },
  {
    id: "7",
    name: "Daniel Park",
    gender: "M",
    email: "daniel@example.com",
    phone: "+1 250-555-0147",
    memberType: "WCI",
    branch: "Kelowna",
    province: "British Columbia",
    attendance: "Maybe",
    accommodation: false,
    transportation: false,
    volunteering: false,
    dietary: "None",
    registered: "2025-01-07",
  },
  {
    id: "8",
    name: "Grace Williams",
    gender: "F",
    email: "grace@example.com",
    phone: "+1 514-555-0258",
    memberType: "WCI",
    branch: "Montreal",
    province: "Quebec",
    attendance: "Yes",
    accommodation: false,
    transportation: true,
    volunteering: false,
    dietary: "None",
    registered: "2025-01-08",
  },
];

// ── Word of the Week ────────────────────────────────────────────────────────
export const mockWordOfWeek = [
  { id: "1", dayNumber: 1, uploadDate: "2025-01-01", duration: "12:34" },
  { id: "2", dayNumber: 2, uploadDate: "2025-01-02", duration: "9:45" },
  { id: "3", dayNumber: 3, uploadDate: "2025-01-03", duration: "14:22" },
  { id: "4", dayNumber: 4, uploadDate: "2025-01-04", duration: "11:08" },
  { id: "5", dayNumber: 5, uploadDate: "2025-01-05", duration: "13:56" },
  { id: "6", dayNumber: 6, uploadDate: "2025-01-06", duration: "10:15" },
];

// ── Wisdom of the Day ───────────────────────────────────────────────────────
export const mockWisdomImages = [
  {
    id: "1",
    day: 1,
    date: "2025-01-01",
    reference: "John 3:16",
    kjv: "For God so loved the world, that he gave his only begotten Son…",
    nlt: "For this is how God loved the world: He gave his one and only Son…",
  },
  {
    id: "2",
    day: 2,
    date: "2025-01-02",
    reference: "Proverbs 3:5-6",
    kjv: "Trust in the LORD with all thine heart; and lean not unto thine own understanding…",
    nlt: "Trust in the LORD with all your heart; do not depend on your own understanding…",
  },
  {
    id: "3",
    day: 3,
    date: "2025-01-03",
    reference: "Psalm 23:1",
    kjv: "The LORD is my shepherd; I shall not want.",
    nlt: "The LORD is my shepherd; I have all that I need.",
  },
  {
    id: "4",
    day: 4,
    date: "2025-01-04",
    reference: "Romans 8:28",
    kjv: "And we know that all things work together for good to them that love God…",
    nlt: "And we know that God causes everything to work together for the good…",
  },
  {
    id: "5",
    day: 5,
    date: "2025-01-05",
    reference: "Philippians 4:13",
    kjv: "I can do all things through Christ which strengtheneth me.",
    nlt: "For I can do everything through Christ, who gives me strength.",
  },
  {
    id: "6",
    day: 6,
    date: "2025-01-06",
    reference: "Isaiah 40:31",
    kjv: "But they that wait upon the LORD shall renew their strength…",
    nlt: "But those who trust in the LORD will find new strength…",
  },
  {
    id: "7",
    day: 7,
    date: "2025-01-07",
    reference: "Jeremiah 29:11",
    kjv: "For I know the thoughts that I think toward you, saith the LORD…",
    nlt: '"For I know the plans I have for you," says the LORD…',
  },
  {
    id: "8",
    day: 8,
    date: "2025-01-08",
    reference: "Matthew 6:33",
    kjv: "But seek ye first the kingdom of God, and his righteousness…",
    nlt: "Seek the Kingdom of God above all else, and live righteously…",
  },
  {
    id: "9",
    day: 9,
    date: "2025-01-09",
    reference: "2 Timothy 1:7",
    kjv: "For God hath not given us the spirit of fear; but of power, and of love…",
    nlt: "For God has not given us a spirit of fear and timidity, but of power…",
  },
  {
    id: "10",
    day: 10,
    date: "2025-01-10",
    reference: "Hebrews 11:1",
    kjv: "Now faith is the substance of things hoped for, the evidence of things not seen.",
    nlt: "Faith is the confidence that what we hope for will actually happen…",
  },
];

// ── Social Links (global) ───────────────────────────────────────────────────
export const mockBranches = [
  // Africa
  {
    id: "1",
    name: "Lagos — Ikeja",
    country: "Nigeria",
    region: "Africa",
    instagram: "@wci_lagos",
    facebook: "WCILagos",
    youtube: "WCILagos",
    tiktok: "@wci_lagos",
    twitter: "@wci_lagos",
  },
  {
    id: "2",
    name: "Abuja",
    country: "Nigeria",
    region: "Africa",
    instagram: "@wci_abuja",
    facebook: "WCIAbuja",
    youtube: "",
    tiktok: "",
    twitter: "@wci_abuja",
  },
  {
    id: "3",
    name: "Nairobi",
    country: "Kenya",
    region: "Africa",
    instagram: "@wci_nairobi",
    facebook: "WCIKenya",
    youtube: "",
    tiktok: "@wci_kenya",
    twitter: "",
  },
  {
    id: "4",
    name: "Accra",
    country: "Ghana",
    region: "Africa",
    instagram: "@wci_ghana",
    facebook: "WCIGhana",
    youtube: "WCIGhana",
    tiktok: "",
    twitter: "@wci_ghana",
  },
  {
    id: "5",
    name: "Johannesburg",
    country: "South Africa",
    region: "Africa",
    instagram: "",
    facebook: "WCISouthAfrica",
    youtube: "",
    tiktok: "",
    twitter: "",
  },
  // North America
  {
    id: "6",
    name: "Toronto — Central",
    country: "Canada",
    region: "North America",
    instagram: "@wci_toronto",
    facebook: "WCIToronto",
    youtube: "WCIToronto",
    tiktok: "@wci_toronto",
    twitter: "@wci_toronto",
  },
  {
    id: "7",
    name: "New York",
    country: "USA",
    region: "North America",
    instagram: "@wci_newyork",
    facebook: "WCINY",
    youtube: "WCINY",
    tiktok: "",
    twitter: "@wci_nyc",
  },
  {
    id: "8",
    name: "Houston",
    country: "USA",
    region: "North America",
    instagram: "@wci_houston",
    facebook: "WCIHouston",
    youtube: "",
    tiktok: "@wci_houston",
    twitter: "",
  },
  {
    id: "9",
    name: "Atlanta",
    country: "USA",
    region: "North America",
    instagram: "",
    facebook: "WCIAtlanta",
    youtube: "",
    tiktok: "",
    twitter: "",
  },
  // Europe
  {
    id: "10",
    name: "London",
    country: "UK",
    region: "Europe",
    instagram: "@wci_london",
    facebook: "WCILondon",
    youtube: "WCILondon",
    tiktok: "@wci_london",
    twitter: "@wci_london",
  },
  {
    id: "11",
    name: "Dublin",
    country: "Ireland",
    region: "Europe",
    instagram: "@wci_ireland",
    facebook: "WCIIreland",
    youtube: "",
    tiktok: "",
    twitter: "@wci_ireland",
  },
  {
    id: "12",
    name: "Amsterdam",
    country: "Netherlands",
    region: "Europe",
    instagram: "",
    facebook: "WCIAmsterdam",
    youtube: "",
    tiktok: "",
    twitter: "",
  },
  {
    id: "13",
    name: "Paris",
    country: "France",
    region: "Europe",
    instagram: "@wci_paris",
    facebook: "",
    youtube: "",
    tiktok: "@wci_paris",
    twitter: "",
  },
  // Asia-Pacific & Middle East
  {
    id: "14",
    name: "Sydney",
    country: "Australia",
    region: "Asia-Pacific",
    instagram: "@wci_sydney",
    facebook: "WCISydney",
    youtube: "",
    tiktok: "",
    twitter: "",
  },
  {
    id: "15",
    name: "Dubai",
    country: "UAE",
    region: "Asia-Pacific",
    instagram: "@wci_dubai",
    facebook: "WCIDubai",
    youtube: "WCIDubai",
    tiktok: "@wci_dubai",
    twitter: "@wci_dubai",
  },
  {
    id: "16",
    name: "Singapore",
    country: "Singapore",
    region: "Asia-Pacific",
    instagram: "",
    facebook: "WCISingapore",
    youtube: "",
    tiktok: "",
    twitter: "",
  },
];
